
#define BIND_GROUP_GLOBAL   0
#define BIND_GROUP_MATERIAL 1

#define BINDING_GLOBALS           0
#define BINDING_SAMPLER           1
#define BINDING_ENTITIES          2
#define BINDING_SHADOWMAP         3
#define BINDING_SHADOWMAP_SAMPLER 4

#define BINDING_MATERIAL 0
#define BINDING_ALBEDO   1

