
#define DESCRIPTOR_SET_GLOBAL 0
#define DESCRIPTOR_SET_MATERIAL 1

#define BINDING_GLOBALS  0
#define BINDING_SAMPLER  1
#define BINDING_ENTITIES 2

#define BINDING_MATERIAL 0
#define BINDING_ALBEDO   1

